/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye7374.views;

import edu.neu.csye7374.Builder.VehicleBuilder;
import edu.neu.csye7374.Builder.EmployeeBuilder;
import edu.neu.csye7374.Vehicle;
import edu.neu.csye7374.VehicleAPI;
import edu.neu.csye7374.VehicleCategory;
import edu.neu.csye7374.Employee;
import edu.neu.csye7374.Factory.VehicleFactory;
import edu.neu.csye7374.Factory.EmployeeFactory;
import edu.neu.csye7374.FileUtil.GeneralFileUtil;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vineeth reddy
 */
public class AddEmployeePanel extends javax.swing.JPanel {
    private List<Employee> employeeList = new ArrayList<>();
    private static AddEmployeePanel instance = null;
    private static String EMP_FILE_NAME = "EmployeesData.csv";
    /**
     * Creates new form AddEmployeePanel
     */
    public AddEmployeePanel() {
    	setBackground(new Color(128, 128, 255));
        initComponents();
        loadData();
    }
    
    public static AddEmployeePanel getInstance(){
        if(instance == null){
            instance= new AddEmployeePanel();
        }
        
        return instance;
    }

    private void loadData() {
        List<String> rawData = GeneralFileUtil.readFile(EMP_FILE_NAME);
        for (String line : rawData) {
            EmployeeBuilder employeeBuilder = new EmployeeBuilder(line);
            employeeList.add(employeeBuilder.build());
        }
        
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        empWage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmpCreateButton = new javax.swing.JButton();
        empId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        empFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empAge = new javax.swing.JTextField();
        empLastName = new javax.swing.JTextField();
        empAgeError = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Id", "First Name", "Last Name", "Age", "Wage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EmployeeTable);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Wage");

        empWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empWageActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new Color(0, 0, 0));
        jLabel9.setText("Emp Id");

        EmpCreateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmpCreateButton.setText("Create");
        EmpCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpCreateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpCreateButtonMouseExited(evt);
            }
        });
        EmpCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCreateButtonActionPerformed(evt);
            }
        });

        empId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("First Name");

        empFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empFirstNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Age");

        empAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empAgeActionPerformed(evt);
            }
        });
        empAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empAgeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empAgeKeyReleased(evt);
            }
        });

        empLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empLastNameActionPerformed(evt);
            }
        });

        empAgeError.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                empAgeErrorInputMethodTextChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Employees");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmpCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(369, 369, 369)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(empFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(empId, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empAgeError)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(empAge, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(empWage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(empLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empWage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empAgeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(EmpCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeTableMouseClicked
//        // TODO add your handling code here:
//        if(booksTable.getSelectedRow() != -1){
//            Book book = booksList.get(booksTable.getSelectedRow());
//            carId.setText(book.getId());
//            carName.setText(book.getBookName());
//            carPrice.setText(book.getBookAuthor());
//            carMfr.setText(book.getBookPublisher());
//            carCategory.setText(String.valueOf(book.getBookEdition()));
//            bookQuantity.setText(String.valueOf(book.getBookQuantity()));
//            booksRemaining.setText(String.valueOf(book.getRemainingBooks()));
//            bookCreateBtn.setEnabled(false);
//            bookUpdateBtn.setEnabled(true);
//            bookDeleteBtn.setEnabled(true);
//            carId.setEnabled(false);
//        }
//        else{
//            carId.setText("");
//            carName.setText("");
//            carPrice.setText("");
//            carMfr.setText("");
//            carCategory.setText("");
//            bookQuantity.setText("");
//            booksRemaining.setText("");
//            bookCreateBtn.setEnabled(true);
//            bookUpdateBtn.setEnabled(false);
//            bookDeleteBtn.setEnabled(false);
//        }

    }//GEN-LAST:event_EmployeeTableMouseClicked

    private void EmpCreateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpCreateButtonMouseEntered
        // TODO add your handling code here:
        EmpCreateButton.setBackground(new Color(0,0,0));
        EmpCreateButton.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_EmpCreateButtonMouseEntered

    private void EmpCreateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpCreateButtonMouseExited
        // TODO add your handling code here:
        EmpCreateButton.setBackground(new Color(255,255,255));
        EmpCreateButton.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_EmpCreateButtonMouseExited

    private void EmpCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCreateButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(empId.getText());
        String firstName = empFirstName.getText();
        String lastName = empLastName.getText();
        Integer age = Integer.parseInt(empAge.getText());
        Double wage = Double.parseDouble(empWage.getText());
 
        
        EmployeeBuilder emplBuilder = new EmployeeBuilder(id, age, firstName, lastName, wage);
        Employee empl = EmployeeFactory.getInstance().getObject(emplBuilder);
        
        employeeList.add((Employee) empl);
        String lineToFile = id + "," + firstName + "," + lastName + "," + age + "," + wage;
        GeneralFileUtil.writeFile(EMP_FILE_NAME, lineToFile, false);
  
        empId.setText("");
        empFirstName.setText("");
        empLastName.setText("");
        empAge.setText("");
        empWage.setText("");

        populateEmployeeTable();
    }//GEN-LAST:event_EmpCreateButtonActionPerformed

    private void empFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empFirstNameActionPerformed

    private void empAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empAgeActionPerformed

    private void empWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empWageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empWageActionPerformed

    private void empLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empLastNameActionPerformed

    private void empIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_empIdActionPerformed

    private void empAgeErrorInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_empAgeErrorInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_empAgeErrorInputMethodTextChanged

    private void empAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empAgeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_empAgeKeyReleased

    private void empAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empAgeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_empAgeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmpCreateButton;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JTextField empAge;
    private javax.swing.JLabel empAgeError;
    private javax.swing.JTextField empFirstName;
    private javax.swing.JTextField empId;
    private javax.swing.JTextField empLastName;
    private javax.swing.JTextField empWage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateEmployeeTable(){
        
        DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
        model.setRowCount(0);
        
        for(Employee employee : employeeList){
            Object[] row = new Object[5];
            
            String[] employeeString = employee.toString().split(",");
            
            for (int i = 0; i < 5; i++) {
                row[i] = employeeString[i];
            }
            
            model.addRow(row);
        }
    }
}
