/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye7374.views;

import edu.neu.csye7374.Builder.VehicleBuilder;
import edu.neu.csye7374.Vehicle;
import edu.neu.csye7374.VehicleAPI;
import edu.neu.csye7374.Manufacturer;
import edu.neu.csye7374.VehicleCategory;
import edu.neu.csye7374.Factory.VehicleFactory;
import edu.neu.csye7374.FileUtil.GeneralFileUtil;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author vineeth reddy
 */
public class AddMfrPanel extends javax.swing.JPanel {
    private List<Manufacturer> mfrList = new ArrayList<>();
    private static AddMfrPanel instance=null;

    private MainFrame mainFrameRef;
    private static String MFR_FILE_NAME = "ManufacturesData.csv"; 

        
    /**
     * Creates new form AddVehiclesPanel
     */
    public AddMfrPanel() {
    	setBackground(new Color(255, 128, 128));
        initComponents();
        loadData();
    }
    
    public static AddMfrPanel getInstance(){
        if(instance == null){
            instance= new AddMfrPanel();
        }
        return instance;
    }

    private void loadData() {
        List<String> rawData = GeneralFileUtil.readFile(MFR_FILE_NAME);
        for (String line : rawData) {
            Manufacturer manufacturer = Manufacturer.getInstance();
            Manufacturer clone = manufacturer.clone();
            clone.setValues(line);
            mfrList.add(clone);
        }
        
        populateMfrTable();
    }
    
    void setMainFrame(MainFrame aThis) {
        this.mainFrameRef = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mfrTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        estYear = new javax.swing.JTextField();
        vehicleCreateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mfrName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vehiclesSold = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        mfrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "EST Year", "noOfVehiclesSold"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mfrTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mfrTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mfrTable);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("EST Year");

        estYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estYearActionPerformed(evt);
            }
        });

        vehicleCreateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleCreateBtn.setText("Create");
        vehicleCreateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vehicleCreateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vehicleCreateBtnMouseExited(evt);
            }
        });
        vehicleCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleCreateBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        mfrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfrNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Vehicles Sold");

        vehiclesSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclesSoldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Manufacturer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(34)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(vehiclesSold, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(estYear, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        					.addGap(32)
        					.addComponent(mfrName, GroupLayout.PREFERRED_SIZE, 551, GroupLayout.PREFERRED_SIZE))
        				.addComponent(vehicleCreateBtn, GroupLayout.PREFERRED_SIZE, 665, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(25, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(216, Short.MAX_VALUE)
        			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 281, GroupLayout.PREFERRED_SIZE)
        			.addGap(227))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(mfrName, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(vehiclesSold, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2)
        				.addComponent(estYear, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6))
        			.addGap(32)
        			.addComponent(vehicleCreateBtn, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addGap(47))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(63)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 283, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(33, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void mfrTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mfrTableMouseClicked
//        // TODO add your handling code here:
//        if(booksTable.getSelectedRow() != -1){
//            Book book = booksList.get(booksTable.getSelectedRow());
//            vehicleId.setText(book.getId());
//            vehicleName.setText(book.getBookName());
//            vehiclePrice.setText(book.getBookAuthor());
//            vehicleMfr.setText(book.getBookPublisher());
//            vehicleCategory.setText(String.valueOf(book.getBookEdition()));
//            bookQuantity.setText(String.valueOf(book.getBookQuantity()));
//            booksRemaining.setText(String.valueOf(book.getRemainingBooks()));
//            bookCreateBtn.setEnabled(false);
//            bookUpdateBtn.setEnabled(true);
//            bookDeleteBtn.setEnabled(true);
//            vehicleId.setEnabled(false);
//        }
//        else{
//            vehicleId.setText("");
//            vehicleName.setText("");
//            vehiclePrice.setText("");
//            vehicleMfr.setText("");
//            vehicleCategory.setText("");
//            bookQuantity.setText("");
//            booksRemaining.setText("");
//            bookCreateBtn.setEnabled(true);
//            bookUpdateBtn.setEnabled(false);
//            bookDeleteBtn.setEnabled(false);
//        }

    }//GEN-LAST:event_mfrTableMouseClicked

    private void vehicleCreateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleCreateBtnMouseEntered
        // TODO add your handling code here:
        vehicleCreateBtn.setBackground(new Color(0,0,0));
        vehicleCreateBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_vehicleCreateBtnMouseEntered

    private void vehicleCreateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleCreateBtnMouseExited
        // TODO add your handling code here:
        vehicleCreateBtn.setBackground(new Color(255,255,255));
        vehicleCreateBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_vehicleCreateBtnMouseExited

    private void vehicleCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleCreateBtnActionPerformed
        // TODO add your handling code here:
        String name= mfrName.getText();
        int noOfVehiclesSold = Integer.parseInt(vehiclesSold.getText());
        int establishedYear = Integer.parseInt(estYear.getText());

//        if(mfrList.stream().map(mfr -> mfr.getVehicleId()).toList().contains("id")){
//            JOptionPane.showMessageDialog(this, "Vehicle with this ID already exists");
//            return;
//        }
        Manufacturer manufact = Manufacturer.getInstance();
        Manufacturer man = manufact.clone();
        man.setManufacturerName(name)
           .setManufacturingYear(establishedYear)
           .setNoOfVehiclesReleased(noOfVehiclesSold);
        
        mfrList.add(man);
        
        String lineToFile = name + "," + noOfVehiclesSold + "," + establishedYear;
        GeneralFileUtil.writeFile(MFR_FILE_NAME, lineToFile, false);
        
        mfrName.setText("");
        vehiclesSold.setText("");
        estYear.setText("");
        

//        populateVehiclesList();
        populateMfrTable();
    }//GEN-LAST:event_vehicleCreateBtnActionPerformed

    private void mfrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfrNameActionPerformed

    private void vehiclesSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclesSoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiclesSoldActionPerformed

    private void estYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton vehicleCreateBtn;
    private javax.swing.JTextField vehiclesSold;
    private javax.swing.JTextField estYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mfrName;
    private javax.swing.JTable mfrTable;
    // End of variables declaration//GEN-END:variables

    private void populateMfrTable(){
        
        DefaultTableModel model = (DefaultTableModel) mfrTable.getModel();
        model.setRowCount(0);
        
        for(Manufacturer mfr : mfrList){
            Object[] row = new Object[4];
            
            String[] mfrString = mfr.toString().split(",");
            
            for (int i = 0; i < 3; i++) {
                row[i] = mfrString[i];
            }
            
            model.addRow(row);
        }
    }
}
