/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye7374.views;

import javax.swing.JSplitPane;
import java.awt.Color;

/**
 *
 * @author vineeth reddy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
    	setBackground(new Color(192, 192, 192));
        initComponents();
        AddMfrPanel mfrPanel = AddMfrPanel.getInstance();
        mfrPanel.setMainFrame(this);
        mainSplitPanel.setRightComponent(mfrPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPanel = new javax.swing.JSplitPane();
        MenuPanel = new javax.swing.JPanel();
        MenuPanel.setBackground(new Color(255, 128, 255));
        addVehicle = new javax.swing.JButton();
        addManufacturers = new javax.swing.JButton();
        orderHistoryBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        addEmployees = new javax.swing.JButton();
        MainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addVehicle.setText("Add Vehicle");
        addVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehiclesActionPerformed(evt);
            }
        });

        addManufacturers.setText("Add Manufacturers");
        addManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManufacturersActionPerformed(evt);
            }
        });

        orderHistoryBtn.setText("Order History");
        orderHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistoryBtnActionPerformed(evt);
            }
        });

        orderBtn.setText("Order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        addEmployees.setText("Add Employees");
        addEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addManufacturers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderHistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addEmployees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addManufacturers)
                .addGap(18, 18, 18)
                .addComponent(addVehicle)
                .addGap(18, 18, 18)
                .addComponent(orderBtn)
                .addGap(18, 18, 18)
                .addComponent(orderHistoryBtn)
                .addGap(18, 18, 18)
                .addComponent(addEmployees)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        mainSplitPanel.setLeftComponent(MenuPanel);

        javax.swing.GroupLayout MainContentPanelLayout = new javax.swing.GroupLayout(MainContentPanel);
        MainContentPanel.setLayout(MainContentPanelLayout);
        MainContentPanelLayout.setHorizontalGroup(
            MainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        MainContentPanelLayout.setVerticalGroup(
            MainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        mainSplitPanel.setRightComponent(MainContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainSplitPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainSplitPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehiclesActionPerformed
        // TODO add your handling code here:
        AddVehiclePanel addVehiclesPanel= AddVehiclePanel.getInstance();
        addVehiclesPanel.setMainFrame(this);
        mainSplitPanel.setRightComponent(addVehiclesPanel);
    }//GEN-LAST:event_addVehiclesActionPerformed

    private void addManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManufacturersActionPerformed
        // TODO add your handling code here:
        AddMfrPanel mfrPanel = AddMfrPanel.getInstance();
        mfrPanel.setMainFrame(this);
        mainSplitPanel.setRightComponent(mfrPanel);
        
    }//GEN-LAST:event_addManufacturersActionPerformed

    private void orderHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistoryBtnActionPerformed
        // TODO add your handling code here:
        OrderHistory orderHistoryPanel = OrderHistory.getInstance();
        mainSplitPanel.setRightComponent(orderHistoryPanel);
    }//GEN-LAST:event_orderHistoryBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
        OrderPanel orderPanel = OrderPanel.getInstance();
        orderPanel.setMainFrame(this);
        mainSplitPanel.setRightComponent(orderPanel);
    }//GEN-LAST:event_orderBtnActionPerformed

    private void addEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeesActionPerformed
        // TODO add your handling code here:
        AddEmployeePanel employeePanel = AddEmployeePanel.getInstance();
        mainSplitPanel.setRightComponent(employeePanel);
    }//GEN-LAST:event_addEmployeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainContentPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton addVehicle;
    private javax.swing.JButton addEmployees;
    private javax.swing.JButton addManufacturers;
    private javax.swing.JSplitPane mainSplitPanel;
    private javax.swing.JButton orderBtn;
    private javax.swing.JButton orderHistoryBtn;
    // End of variables declaration//GEN-END:variables

    public JSplitPane getMainSplitPanel() {
        return mainSplitPanel;
    }
}