/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.csye7374.views;

import edu.neu.csye7374.Builder.VehicleBuilder;
import edu.neu.csye7374.VehicleAPI;
import edu.neu.csye7374.FileUtil.GeneralFileUtil;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author vineeth reddy
 */
public class OrderHistory extends javax.swing.JPanel {

    private String ORDERS_FILE_NAME = "OrdersData.csv";
    private static OrderHistory instance = null;

    /**
     * Creates new form OrderHistory
     */
    public OrderHistory() {
    	setBackground(new Color(128, 255, 128));
        initComponents();
        loadData();
    }
    
    public static OrderHistory getInstance() {
        if (instance == null) {
            instance = new OrderHistory();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderHistoryTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(793, 581));

        orderHistoryTable.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        	},
        	new String[] {
        		"Vehicle Name", "Category", "Mfr Name", "Delivery Type", "Order Cost"
        	}
        ));
        jScrollPane1.setViewportView(orderHistoryTable);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Previous Order History");

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(49, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 687, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 281, GroupLayout.PREFERRED_SIZE)
        					.addGap(191)
        					.addComponent(refreshBtn)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(refreshBtn)
        				.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        			.addGap(86)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        			.addGap(374))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderHistoryTable;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
    
    private void loadData() {
        List<String> rawData = GeneralFileUtil.readFile(ORDERS_FILE_NAME);
        DefaultTableModel model = (DefaultTableModel) orderHistoryTable.getModel();
        model.setRowCount(0);
        for (String line : rawData) {
            Object[] row = new Object[5];

            String[] vehicleString = line.split(",");
            int i;
            for (i = 0; i < 5; i++) {
                row[i] = vehicleString[i];
            }

            model.addRow(row);
        }
        
    }

}
